---
title: "Untitled"
author: "Xuran Yan"
date: '2022-06-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load("easySHARE_rel8_0_0.rda")
easyshare = easySHARE_rel8_0_0
# select variables
easyshare <- easyshare %>%  dplyr::select(c(wave, age, female, country_mod, isced1997_r, chronic_mod, ever_smoked, smoking, br010_mod, eurod, bmi2, sp002_mod, sp008_, br015_, recall_1, recall_2))
# rename
easyshare <- easyshare %>% rename(education = isced1997_r, drinking = br010_mod, depression = eurod, vigorous_act = br015_)

# set missing value as NA
easyshare[easyshare < 0] <- NA

easyshare$age <- cut(easyshare$age, breaks = c(0,seq(55,90,5),120), ordered_result = TRUE, right = FALSE)
#easyshare$casp <- cut(easyshare$casp, breaks = c(12, quantile(easyshare$casp, probs = c(.1,.4),na.rm=TRUE),48), ordered_result = TRUE)
easyshare$female <- factor(easyshare$female, ordered = TRUE)
easyshare$education <- factor(easyshare$education, ordered = TRUE)
easyshare$chronic_mod <- factor(easyshare$chronic_mod, ordered = TRUE)
#easyshare$ever_smoked <- factor(easyshare$ever_smoked, ordered = TRUE)
easyshare$drinking <- factor(easyshare$drinking, ordered = TRUE)
easyshare$depression <- factor(easyshare$depression, ordered = TRUE)
easyshare$bmi2 <- factor(easyshare$bmi2, ordered = TRUE)
easyshare$vigorous_act <- factor(easyshare$vigorous_act, ordered = TRUE)
#easyshare$sleep <- factor(easyshare$sleep, ordered = TRUE)
# easyshare$mar_stat <- factor(easyshare$mar_stat, ordered = TRUE)
# easyshare$recieve_help <- factor(easyshare$recieve_help, ordered = TRUE)
# easyshare$give_help <- factor(easyshare$give_help, ordered = TRUE)

# create a composite cognitive score as a proxy for dementia severity
easyshare$cogscore = easyshare$recall_1 + easyshare$recall_2
easyshare$cogscore <- cut(easyshare$cogscore, breaks = c(0, quantile(easyshare$cogscore, probs = c(.1,.4),na.rm=TRUE),29), ordered_result = TRUE)

# divided country into 4 areas
easyshare$country_area <- ifelse(easyshare$country_mod %in% c(203,348,428,703), "E", ifelse(easyshare$country_mod %in% c(40,56,250,276,442,528,756), "W", ifelse(easyshare$country_mod %in% c(208,233,246,372,440,616,752), "N", "S")))
easyshare$country_area<- factor(easyshare$country_area, ordered = TRUE)

# create a social variable
easyshare$social_help <- easyshare$sp002_mod + easyshare$sp008_
easyshare$social_help <- factor(easyshare$social_help, ordered = TRUE)

# physical inactivity
# easyshare$daily_act <- easyshare$adla + easyshare$iadlza
# easyshare$daily_act <- factor(easyshare$daily_act, ordered = TRUE)

easyshare$smoke <- easyshare$ever_smoked + easyshare$smoking
easyshare$smoke <- factor(easyshare$smoke, ordered = TRUE)

easyshare_sub = easyshare[easyshare$wave==5,]
```

```{r, fig.height=15, fig.width=24}
p1 = ggplot() + geom_bar(aes(x = easyshare_sub$age),color="darkblue", fill="lightblue")+  labs(x ="Age")
p2 = ggplot() + geom_bar(aes(x = easyshare_sub$cogscore),color="darkblue", fill="lightblue")+  labs(x ="Cogntive impairment")
p3 = ggplot() + geom_bar(aes(x = easyshare_sub$sleep),color="darkblue", fill="lightblue")+  labs(x ="sleep")

p4 = ggplot() + geom_bar(aes(x = easyshare_sub$country_area),color="darkblue", fill="lightblue")+  labs(x ="country_area(country)")
p5 = ggplot() + geom_bar(aes(x = easyshare_sub$female),color="darkblue", fill="lightblue")+  labs(x ="Gender")
p6 = ggplot() + geom_bar(aes(x = easyshare_sub$education),color="darkblue", fill="lightblue")+  labs(x ="Education") +  geom_density(color = "black", fill = "gray")
p7 = ggplot() + geom_bar(aes(x = easyshare_sub$chronic_mod),color="darkblue", fill="lightblue")+  labs(x ="Number of chronic diseases")
#p8 = ggplot() + geom_bar(aes(x = easyshare_sub$ever_smoked),color="darkblue", fill="lightblue")+  labs(x ="Ever smoked daily")
p8 = ggplot() + geom_bar(aes(x = easyshare_sub$smoke),color="darkblue", fill="lightblue")+  labs(x ="Smoke")
p9 = ggplot() + geom_bar(aes(x = easyshare_sub$drinking),color="darkblue", fill="lightblue")+  labs(x ="Drinking behavior")
p10 = ggplot() + geom_bar(aes(x = easyshare_sub$depression),color="darkblue", fill="lightblue")+  labs(x ="Depression scale")
p11 = ggplot() + geom_bar(aes(x = easyshare_sub$bmi2),color="darkblue", fill="lightblue")+  labs(x ="Body Mass Index")
p12 = ggplot() + geom_bar(aes(x = easyshare_sub$vigorous_act),color="darkblue", fill="lightblue")+  labs(x ="vigorous activities")
p13 = ggplot() + geom_bar(aes(x = easyshare_sub$mar_stat),color="darkblue", fill="lightblue")+  labs(x ="mar_stat")
p14 = ggplot() + geom_bar(aes(x = easyshare_sub$social_help),color="darkblue", fill="lightblue")+  labs(x ="social")
#p15 = ggplot() + geom_bar(aes(x = easyshare_sub$social_help),color="darkblue", fill="lightblue")+  labs(x ="Activities of daily living index (high: has difficulties)")
 
grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, nrow = 3)
```

```{r}
library(forcats)
#age:
#easyshare_sub$age=easyshare_sub$age %>% fct_collapse("<60" = c("[0,50)","[50,60)"))
easyshare_sub$age=easyshare_sub$age %>% fct_collapse(">80" = c("[80,85)", "[85,90)","[90,120)"))
# cognitive score
levels(easyshare_sub$cogscore) <- c("low","moderate","high")
# gender
levels(easyshare_sub$female) <- c("male","female")
# education
levels(easyshare_sub$education) <- list("basic" = c("1","2"), "secondary" = c("3","4"), "tertiary" = c("5","6"), "other" = c("0","95","97"))
# Number of chronic diseases
# easyshare_sub$chronic_mod=easyshare_sub$chronic_mod %>% fct_collapse(">=3" = c("3","4","5","6","7","8","9","10"))
levels(easyshare_sub$chronic_mod) <- list("none" = "0", "less" = c("1","2"), "much" = c("3","4","5","6","7","8","9","10"))
# smoke
# levels(easyshare_sub$ever_smoked) <- c("yes","no")
levels(easyshare_sub$smoke) <- list("non-smoke" = "10", "smoke" = c("2","6"))
# drinking
levels(easyshare_sub$drinking) <- list("low" = c("1","2"), "moderate" = c("3","4","5"), "high" = c("6","7"))
# depression
levels(easyshare_sub$depression) <- list("low" = c("0","1","2","3"), "moderate" = c("4","5","6","7"), "high" = c("8","9","10","11","12"))
# body mass index
#levels(easyshare_sub$bmi2) <- list("normal" = c("1","2"), "overweight" = "3", "obese" = "4")
# received and given help
#levels(easyshare_sub$social_help) <- list("social" = c("2","6"), "no social" = "10")
levels(easyshare_sub$social_help) <- list("social" = "2", "moderate" = "6", "no social" = "10")
# levels(easyshare_sub$recieve_help) <- c("yes","no")
# levels(easyshare_sub$give_help) <- c("yes","no")
# vigorous activities
#levels(easyshare_sub$vigorous_act) <- list("frequent" = "1", "moderate" = c("2","3"), "never" = "4")
# sleep
#levels(easyshare_sub$sleep) <- c("no","yes")

# drop useless variables: useless and inbalence 
# easyshare_sub = subset(easyshare_sub, select=-c(wave, country_mod, recall_1, recall_2, adla, iadlza, mar_stat))
easyshare_sub = subset(easyshare_sub, select=-c(wave, country_mod, recall_1, recall_2, ever_smoked, smoking, sp002_mod, sp008_))
#### drop variables NA
easyshare_sub_narm <- easyshare_sub[complete.cases(easyshare_sub),]
```

```{r, fig.height=15, fig.width=24}
p1 = ggplot() + geom_bar(aes(x = easyshare_sub$age),color="darkblue", fill="lightblue")+  labs(x ="Age")
p2 = ggplot() + geom_bar(aes(x = easyshare_sub$cogscore),color="darkblue", fill="lightblue")+  labs(x ="Cogntive impairment")
p3 = ggplot() + geom_bar(aes(x = easyshare_sub$sleep),color="darkblue", fill="lightblue")+  labs(x ="Trouble with sleeping")

p4 = ggplot() + geom_bar(aes(x = easyshare_sub$country_area),color="darkblue", fill="lightblue")+  labs(x ="Country region")
p5 = ggplot() + geom_bar(aes(x = easyshare_sub$female),color="darkblue", fill="lightblue")+  labs(x ="Gender")
p6 = ggplot() + geom_bar(aes(x = easyshare_sub$education),color="darkblue", fill="lightblue")+  labs(x ="Education") +  geom_density(color = "black", fill = "gray")
p7 = ggplot() + geom_bar(aes(x = easyshare_sub$chronic_mod),color="darkblue", fill="lightblue")+  labs(x ="Number of chronic diseases")
#p8 = ggplot() + geom_bar(aes(x = easyshare_sub$ever_smoked),color="darkblue", fill="lightblue")+  labs(x ="Ever smoked daily")
p8 = ggplot() + geom_bar(aes(x = easyshare_sub$smoke),color="darkblue", fill="lightblue")+  labs(x ="Smoke")
p9 = ggplot() + geom_bar(aes(x = easyshare_sub$drinking),color="darkblue", fill="lightblue")+  labs(x ="Drinking behavior")
p10 = ggplot() + geom_bar(aes(x = easyshare_sub$depression),color="darkblue", fill="lightblue")+  labs(x ="Depression scale")
p11 = ggplot() + geom_bar(aes(x = easyshare_sub$bmi2),color="darkblue", fill="lightblue")+  labs(x ="Body Mass Index")
p12 = ggplot() + geom_bar(aes(x = easyshare_sub$vigorous_act),color="darkblue", fill="lightblue")+  labs(x ="vigorous activities")
# p13 = ggplot() + geom_bar(aes(x = easyshare_sub$mar_stat),color="darkblue", fill="lightblue")+  labs(x ="mar_stat")
# p14 = ggplot() + geom_bar(aes(x = easyshare_sub$daily_act),color="darkblue", fill="lightblue")+  labs(x ="Activities of daily living index (high: has difficulties)")
 p15 = ggplot() + geom_bar(aes(x = easyshare_sub$social_help),color="darkblue", fill="lightblue")+  labs(x ="social")
 
grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12,p15, nrow = 3)
```
-------------------------- choose model

```{r}
# Constraint-based algorithms
myblacklist = matrix(c("cogscore","age",
                   "female","age",
                   'country_area', "age",
                   "education","age",
                   "chronic_mod","age",
                   'smoke', "age",
                   'drinking', "age",
                   'depression', "age",
                   'bmi2', "age",
                   'vigorous_act', "age",
                   "age","female",
                   "country_area","female",
                   "education","female",
                   "cogscore","female",
                   'chronic_mod', "female",
                   'smoke', "female",
                   'drinking', "female",
                   'depression', "female",
                   'bmi2', "female",
                   'vigorous_act', "female",
                   "age","country_area",
                   "female","country_area",
                   "education","country_area",
                   "cogscore","country_area",
                   'chronic_mod', "country_area",
                   'smoke', "country_area",
                   'drinking', "country_area",
                   'depression', "country_area",
                   'bmi2', "country_area",
                   'vigorous_act', "country_area",
                   "cogscore","age",
                   "cogscore","female",
                   "cogscore","education",
                   "cogscore",'chronic_mod', 
                   "cogscore",'smoke', 
                   "cogscore","country_area",
                   "cogscore",'drinking', 
                   "cogscore",'depression', 
                   "cogscore",'bmi2', 
                   "cogscore", 'vigorous_act',
                   "cogscore",'social_help', 
                   'social_help', "country_area",
                   'social_help', "female",
                   'social_help', "age",
                   "smoke","education",
                   "drinking","education",
                   'vigorous_act',"education",
                   "bmi2","education"), 
                 byrow = TRUE, ncol=2, dimnames =list(NULL,c("from","to")))

mywhitelist = matrix(c("drinking","chronic_mod",
                       "smoke","chronic_mod",
                       "social_help", "depression"),
                 byrow = TRUE, ncol=2, dimnames =list(NULL,c("from","to")))

mywhitelist = matrix(c("drinking","chronic_mod",
                       "smoke","chronic_mod"),
                 byrow = TRUE, ncol=2, dimnames =list(NULL,c("from","to")))
```

```{r}
# iamb
easyshare_sub.iamb =iamb(easyshare_sub, blacklist = myblacklist,whitelist = mywhitelist, test="mi")
graphviz.plot(easyshare_sub.iamb)

# hc(bic)
easyshare_sub.hc =hc(easyshare_sub_narm, blacklist = myblacklist, whitelist = mywhitelist, score="bic")
graphviz.plot(easyshare_sub.hc)

# hc(bde)
easyshare_sub.hc2 =hc(easyshare_sub_narm, blacklist = myblacklist, whitelist = mywhitelist, score="bde")
graphviz.plot(easyshare_sub.hc2)
```

```{r}
# choose the learning algorithm with smallest expected loss, result: choose hc(bic)
bn.cv(data = easyshare_sub_narm, bn = easyshare_sub.iamb, loss = "pred", loss.args = list(target = "cogscore"))
bn.cv(data = easyshare_sub_narm, bn = easyshare_sub.hc, loss = "pred", loss.args = list(target = "cogscore"))
bn.cv(data = easyshare_sub_narm, bn = easyshare_sub.hc2, loss = "pred", loss.args = list(target = "cogscore"))
```


```{r}
# add the line from social_help to depression: can not add
dag=easyshare_sub.iamb
dag=set.arc(dag, from = "social_help", to= "depression")
bn.cv(data = easyshare_sub_narm, bn = dag, loss = "pred", loss.args = list(target = "cogscore"))
```


```{r}
# drop the line from country_area to social_help: can drop
dag2=easyshare_sub.iamb
dag2=drop.arc(dag2,  from = "country_area", to= "social_help")
bn.cv(data = easyshare_sub_narm, bn = dag2, loss = "pred", loss.args = list(target = "cogscore"))
```



```{r}
# add the line from social_help to depression: can not add
dag3=dag2
dag3=set.arc(dag3, from = "social_help", to= "depression")
bn.cv(data = easyshare_sub_narm, bn = dag3, loss = "pred", loss.args = list(target = "cogscore"))
```

-------------------------------------- fit the model

```{r}
# fit parameters
bn.bayes = bn.fit(easyshare_sub.iamb, data=easyshare_sub_narm, method = "bayes",iss=10)
bn.bayes$education
bn.fit.barchart(bn.bayes$education)
```


```{r, fig.height=15, fig.width=20}
age.lv = levels(easyshare_sub_narm$age)
gender.lv = levels(easyshare_sub_narm$female)
edu.lv = levels(easyshare_sub_narm$education)
dep.lv = levels(easyshare_sub_narm$depression)

p=c()
for (i in 1:dim(bn.bayes$cogscore$prob)[3]){
  for (j in 1:dim(bn.bayes$cogscore$prob)[4]){
    for (k in 1:dim(bn.bayes$cogscore$prob)[5]){
      for (t in 1:24){
        p[t] = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3), y=matrix(t(bn.bayes$cogscore$prob[,,i,j,k]), ncol =1), 
                           color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
        geom_point() +
        geom_line() + 
        scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
        labs(x = "Age", y= "Conditional probability", color = "Cognitive score", 
             title = paste(gender.lv[i],paste(edu.lv[j],"education",sep=' '),paste(dep.lv[k],"depression",sep=' '),sep=', '))
      }
      
    }
  }
}

grid.arrange(p, nrow = 3)
```


```{r, fig.height=15, fig.width=20}
# age as abscissa
p1 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,1,1,1]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Male, Basic education, Low depression")

p2 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,2,1,1]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Female, Basic education, Low depression")

p3 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,1,2,1]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Male, Secondary education, Low depression")

p4 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,2,2,1]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Famale, Secondary education, Low depression")

p5 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,1,3,1]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Male, Tertiary education, Low depression")

p6 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,2,3,1]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Female, Tertiary education, Low depression")

p7 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,1,4,1]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Male, Other education, Low depression")

p8 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,2,4,1]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Famale, Other education, Low depression")
########################
p9 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,1,1,2]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Male, Basic education, Moderate depression")

p10 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,2,1,2]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Female, Basic education, Moderate depression")

p11 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,1,2,2]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Male, Secondary education, Moderate depression")

p12 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,2,2,2]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Famale, Secondary education, Moderate depression")

p13 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,1,3,2]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Male, Tertiary education, Moderate depression")

p14 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,2,3,2]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Female, Tertiary education, Moderate depression")

p15 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,1,4,2]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Male, Other education, Moderate depression")

p16 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,2,4,2]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Famale, Other education, Moderate depression")

grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12,p13,p14,p15,p16, nrow = 4)
```


```{r, fig.height=15, fig.width=20}
##################################
p5 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,1,2]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Other education, Moderate quality of life")

p6 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,2,2]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Basic education, Moderate quality of life")

p7 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,3,2]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Secondary education, Moderate quality of life")

p8 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,4,2]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Tertiary education, Moderate quality of life")

########################

p9 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,1,3]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Other education, High quality of life")

p10 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,2,3]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Basic education, High quality of life")

p11 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,3,3]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Secondary education, High quality of life")

p12 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,4,3]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Tertiary education, High quality of life")


grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, nrow = 3)
```

```{r}
p1 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,1,1]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Other education, Low quality of life")

p2 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,2,1]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Basic education, Low quality of life")

p3 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,3,1]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Secondary education, Low quality of life")

p4 = ggplot(mapping = aes(x = rep(seq(1:length(levels(easyshare_sub_narm$age))),3),
                     y=matrix(t(bn.bayes$cogscore$prob[,,4,1]), ncol =1), color = rep(levels(easyshare_sub_narm$cogscore), each = length(levels(easyshare_sub_narm$age))))) + 
  geom_point() +
  geom_line() +
  scale_x_discrete(breaks=seq(1:length(levels(easyshare_sub_narm$age))),
        labels=levels(easyshare_sub_narm$age)) +
  labs(x = "Age", y= "Conditional probability", color = "Cognitive score", title ="Tertiary education, Low quality of life")
grid.arrange(p1, p2, p3, p4, nrow = 2)
```


```{r}
library(MASS)
olr.fit =polr(education ~ age+female+country_area, data = easyshare_sub_narm)
distedu = predict(olr.fit, newdata= data.frame(age=levels(easyshare_sub_narm$age),female=levels(easyshare_sub_narm$female),country_area=levels(easyshare_sub_narm$country_area)),type="p")
edu.lv = levels(easyshare_sub_narm$education)
age.lv = levels(easyshare_sub_narm$age)
female.lv = levels(easyshare_sub_narm$female)
country_area.lv = levels(easyshare_sub_narm$country_areaage)
distedu = array(t(distedu), dim=c(length(edu.lv),length(age.lv),length(female.lv),length(country_area.lv)), 
                dimnames = list(education = edu.lv, age = age.lv, female = female.lv,country_area=country_area.lv))
bn.bayes2 = bn.bayes
bn.bayes2$education = distedu
bn.fit.barchart(bn.bayes2$education)
```


















```{r}
#easyshare_sub = easyshare[easyshare$wave==5,]
library(forcats)
#age: 
easyshare_sub$age=easyshare_sub$age %>% fct_collapse("<60" = c("[0,50)","[50,60)"))
easyshare_sub$age=easyshare_sub$age %>% fct_collapse(">80" = c("[80,90)","[90,120)"))
# education
easyshare_sub$education=easyshare_sub$education %>% fct_collapse("1" = c("1","2"))
easyshare_sub$education=easyshare_sub$education %>% fct_collapse("2" = c("3","4"))
easyshare_sub$education=easyshare_sub$education %>% fct_collapse("3" = c("5","6") )
easyshare_sub$education=easyshare_sub$education %>% fct_collapse("4" = c("95","0","97"))
# Number of chronic diseases
easyshare_sub$chronic_mod=easyshare_sub$chronic_mod %>% fct_collapse(">=3" = c("3","4","5","6","7","8","9","10"))
# drinking
levels(easyshare_sub$drinking) <- list("1" = "1", "2" = c("2","3"), "3" = c("4","5","6"), "4" = "7")
# depression
easyshare_sub$depression=easyshare_sub$depression %>% fct_collapse("4" = c("4","5","6","7","8","9","10","11","12"))
# vigorous activities
levels(easyshare_sub$vigorous_act) <- list("1" = "1", "2" = c("2","3"), "3" = "4")


# drop useless variables: useless and inbalence 
easyshare_sub = subset(easyshare_sub, select=-c(wave, country_mod, recall_1, recall_2, mar_stat))
#### drop variables NA
easyshare_sub_narm <- easyshare_sub[complete.cases(easyshare_sub),]

# easyshare_sub$age <- factor(easyshare_sub$age)
# easyshare_sub$education <- factor(easyshare_sub$education, ordered = TRUE)
# easyshare_sub$chronic_mod <- factor(easyshare_sub$chronic_mod, ordered = TRUE)
# easyshare_sub$drinking <- factor(easyshare_sub$drinking, ordered = TRUE)
# easyshare_sub$depression <- factor(easyshare_sub$depression, ordered = TRUE)
# easyshare_sub$vigorous_act <- factor(easyshare_sub$vigorous_act, ordered = TRUE)

easyshare_sub = easyshare[easyshare$wave==5,]
easyshare_sub$age[easyshare_sub$age %in% c("[0,50)","[50,60)")]="50"
easyshare_sub$age[easyshare_sub$age=="[80,90)" | easyshare_sub$age=="[90,120)"]="80"
easyshare_sub$age <- factor(easyshare_sub$age)

easyshare_sub$education[easyshare_sub$education == "1" | easyshare_sub$education == "2"] = "1"
easyshare_sub$education[easyshare_sub$education == "3" | easyshare_sub$education == "4"] = "2"
easyshare_sub$education[easyshare_sub$education == "5" | easyshare_sub$education == "6"] = "3"
easyshare_sub$education[easyshare_sub$education == "0" | easyshare_sub$education == "95"| easyshare_sub$education == "97"] = "4"
easyshare_sub$education <- factor(easyshare_sub$education, ordered = TRUE)

easyshare_sub$chronic_mod[easyshare_sub$chronic_mod %in% c("3","4","5","6","7","8","9","10")]="3"
easyshare_sub$chronic_mod <- factor(easyshare_sub$chronic_mod, ordered = TRUE)

easyshare_sub$drinking[easyshare_sub$drinking=="2"|easyshare_sub$drinking=="3"]="2"
easyshare_sub$drinking[easyshare_sub$drinking=="4"|easyshare_sub$drinking=="5"|easyshare_sub$drinking=="6"]="3"
easyshare_sub$drinking[easyshare_sub$drinking=="7"]="4"
easyshare_sub$drinking <- factor(easyshare_sub$drinking, ordered = TRUE)

easyshare_sub$depression[easyshare_sub$depression %in% c("4","5","6","7","8","9","10","11","12")]="4"
easyshare_sub$depression <- factor(easyshare_sub$depression, ordered = TRUE)

easyshare_sub$vigorous_act[easyshare_sub$vigorous_act=="2"|easyshare_sub$vigorous_act=="3"]="2"
easyshare_sub$vigorous_act[easyshare_sub$vigorous_act=="4"]="3"
easyshare_sub$vigorous_act <- factor(easyshare_sub$vigorous_act, ordered = TRUE)

# easyshare_sub$age <- factor(easyshare_sub$age)
# easyshare_sub$education <- factor(easyshare_sub$education, ordered = TRUE)
# easyshare_sub$chronic_mod <- factor(easyshare_sub$chronic_mod, ordered = TRUE)
# easyshare_sub$drinking <- factor(easyshare_sub$drinking)
# easyshare_sub$depression <- factor(easyshare_sub$depression)
# easyshare_sub$vigorous_act <- factor(easyshare_sub$vigorous_act)
```